### PR TITLE
Update on Boulder calification

### LINKED ISSUE #4: Boulder was better than alright m8
Dear @abdulajet, Boulder was better than alright m8. Its amazing right @elliotwhitehead ?

### PR DESCRIPTION
**Pull request by casassg**
Discussing with @elliotwhitehead, we feel that alright is not enough qualification for Boulder. Edited the clarification to make sure people know that Boulder is *amazing*.

Closes #4

### CODE REVIEW

**Review by abdulajet — CHANGES_REQUESTED** [review]
its a bit too emotive for me, try again

**Comment by casassg** [comment]
@elliotwhitehead pls halp

**Comment by AlbertSuarez** [comment]
I would qualify it as `nice` more than `amazing`.

**Comment by abdulajet** [comment]
`nice` sounds good to me

**Comment by casassg** [comment]
Updated with `nice`

**Review by abdulajet — APPROVED** [review]
LGTM

**Comment by casassg** [comment]
I can't merge it m8!

**Comment by abdulajet** [comment]
👍

**Pull request merged**
